version: '3.9'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: home_budget
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:6.0

  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - redis
      - db
    environment:
      REDIS_URL: redis://redis:6379/0
    volumes:
      - .:/app

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"

    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://postgres:password@db/home_budget
      REDIS_URL: redis://redis:6379/0

volumes:
  db_data:
